//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektniZadatak
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kupac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupac()
        {
            this.Racuns = new HashSet<Racun>();
        }

        
        public int IDKupac { get; set; }

        [Required(ErrorMessage = "Ime kupca je obavezno!")]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Prezime kupca je obavezno!")]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Email kupca je obavezan!")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Unesite ispravnu E-mail adresu!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Email kupca je obavezan!")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Unesite ispravan broj mobilnog telefona")]
        public string Telefon { get; set; }

        [Display(Name = "Grad")]
        [Required(ErrorMessage = "Grad je obavezan!")]
        public Nullable<int> GradID { get; set; }
    
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}
