//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektniZadatak
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Potkategorija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Potkategorija()
        {
            this.Proizvods = new HashSet<Proizvod>();
        }
    
        public int IDPotkategorija { get; set; }

        [Required(ErrorMessage = "Polje kategorija je obavezno!")]
        [Display(Name = "Kategorija")]
        
        public int KategorijaID { get; set; }

        [Display(Name = "Naziv")]
        [Required(ErrorMessage = "Naziv potkategorije je obavezan!")]
        public string NazivPotkategorije { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvod> Proizvods { get; set; }
    }
}
